- name: "Fetching Custom Attributes{{ ':' }} {{ service_selected }}"
  uri: url={{ service_selected }}?attributes=custom_attributes method=GET status_code=200
      headers={"Content-type":"application/json","Accept":"application/json","X-Auth-Token":"{{ authentication_token }}"}
  register: custom_attributes

- name: Fetching SSH Access information (Environment Info 5)
  set_fact: ssh_host_target_host={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 5'].value")|first|regex_replace("^SSH Access[:] ssh ", "") }}
- set_fact: target_host_user="{{ ssh_host_target_host | regex_replace("[@](.*)$", "") }}"
- set_fact: target_host_name="{{ ssh_host_target_host | regex_replace("^(.*)[@]", "") }}"

- name: Fetching Password for Host (Environment Info 6)
  set_fact: target_host_password={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 6'].value")|first|regex_replace("^SSH password[:] ", "") }}

- name: Fetching AWS Key (Environment Info 3)
  set_fact: aws_key={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 3'].value")|first|regex_replace("^aws_access_key_id [=] ", "") }}

- name: Fetching AWS Secret (Environment Info 4)
  set_fact: aws_secret={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 4'].value")|first|regex_replace("^aws_secret_access_key [=] ", "") }}

- name: Fetching GUID 
  set_fact: guid={{ custom_attributes|json_query("json.custom_attributes[?name=='GUID'].value")|first }}

- name: Top Level Domain (Environment Info 0)
  set_fact: top_level_domain={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 0'].value")|first|regex_replace("^Top level domain[:] ", "") }}
